ALTER TABLE `session_table`
ADD `start_date` DATE NOT NULL ,
ADD `end_date` DATE NOT NULL ,
ADD `created_at` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
ADD `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
ADD `current` VARCHAR(10) NULL DEFAULT NULL ;